In [ ]:
import numpy as np

A = np.array([[1,   2,  3],
              [21, 35, 63],
              [17, 28, 39]])

print('The value of the determinant of A:', np.linalg.det(A))
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

The value of the determinant of A: 84.00000000000006
Inverse of A:
 [[-4.75        0.07142857  0.25      ]
 [ 3.         -0.14285714  0.        ]
 [-0.08333333  0.07142857 -0.08333333]]


In [ ]:
# Singular matrices (whose det is ~0) are NOT Invertible
A1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print('The value of the determinant of A1:', np.linalg.det(A1))
A1_inv = np.linalg.inv(A1)
A1_inv

The value of the determinant of A1: 0.0


LinAlgError: ignored

In [ ]:
I = np.eye(3) # Identity matrix of (3,3)
I.astype('int32')  # typecasting or Typeconversion

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [ ]:
I.dtype

dtype('float64')

In [ ]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones = np.ones((4,4))*100
ones

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [ ]:
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.matmul(A, B).T

array([[ 30, 602, 402],
       [ 36, 721, 486],
       [ 42, 840, 570]])

In [ ]:
np.matmul(B.T, A.T)

array([[ 30, 602, 402],
       [ 36, 721, 486],
       [ 42, 840, 570]])

# Rank of a Matrix
The rank of a matrix is a fundamental concept in linear algebra. It refers to the maximum number of linearly independent column vectors in the matrix or the maximum number of linearly independent row vectors in the matrix. Both definitions are equivalent.

**What Does Matrix Rank Mean?**

- **In terms of linear independence:** If you have a set of vectors, they are linearly independent if no vector in the set is a combination of other vectors. The rank of a matrix is the largest subset of rows or columns that is linearly independent. So, for a given matrix, if you have the maximum of 'r' rows (or columns) that are linearly independent, then no other set with more than 'r' rows (or columns) can be linearly independent, and thus the rank is 'r'.


**Applications of Matrix Rank:**

1. **Solving Systems of Linear Equations:** The rank is used to determine whether a system of linear equations has a unique solution, no solution, or infinitely many solutions.

2. **Economics and Business:** In input-output analysis, which examines the interdependencies between different industries, the rank of the matrix can reveal the chain of effects of one sector on others.

3. **Engineering and Computer Science:** In image processing, the rank of matrices representing digital images is studied for image compression. Lower-rank approximations can significantly compress the size of the image data.

4. **Data Science:** In machine learning, particularly in the reduction of dimensionality of data, techniques like Principal Component Analysis (PCA) work by computing a low-rank approximation of the data matrix.

5. **Psychometrics:** In factor analysis, used for assessing the validity of tests or questionnaires, the rank of a matrix determines the minimum number of common factors influencing a set of measures.

```

```

This code calculates and prints the rank of matrix A. The `matrix_rank` function uses the Singular Value Decomposition (SVD) method to calculate the rank accurately, including for matrices with zero or very small singular values.

In [ ]:
import numpy as np

# # Creating a 2x3 matrix
A = np.array([[1,   2,  3],
              [21, 35, 63],
              [17, 28, 39]])

# Calculating the rank of the matrix
rank = np.linalg.matrix_rank(A)

print("Rank of the matrix:", rank)

Rank of the matrix: 3


In [ ]:
# # Creating a 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [50, 70, 90]])

# A[2]= 3*A[0] - 5*A[1]   # 3rd row as linear combination of the 1st 2 rows
A[:,1] = 5*A[:,0]  # 2nd col as multiple of the 1st col
A[:,2] = 3*A[:,0] + 5*A[:,1] # 3rd col as linear combination of the 1st 2 cols

print(A)
# Calculating the rank of the matrix
rank = np.linalg.matrix_rank(A)

print("Rank of the matrix:", rank)

[[   1    5   28]
 [   4   20  112]
 [  50  250 1400]]
Rank of the matrix: 1


In [ ]:
np.linalg.inv(A)

LinAlgError: ignored

In [ ]:
# # Creating a 2x3 matrix
A = np.array([[1, 2,  2],
              [4, 5, 20],
              [5, 7, 35]])

# Calculating the rank of the matrix
rank = np.linalg.matrix_rank(A)

print("Rank of the matrix:", rank)

Rank of the matrix: 3


# Vector Dot Product
The vector dot product, also known as the scalar product, is a fundamental operation in linear algebra with numerous practical applications in various fields, including physics, engineering, computer science, business, and data science. It involves the multiplication of two vectors, resulting in a scalar value. This operation captures essential information about the vectors' magnitude and direction, particularly their cosine similarity. Here are some real-world applications and specific use-cases in business and data science:

**1. Physics and Engineering:**
   - **Work Done by a Force:** In physics, the dot product is used to calculate the work done by a force. Work is calculated as the dot product of force and displacement vectors. This concept is fundamental in mechanics, helping engineers understand and optimize mechanical systems.
   - **Projection in Navigation Systems:** Engineers use the dot product in calculating the projection of one vector onto another, useful in navigation, robotics, and aeronautics for determining paths or course directions.

**2. Computer Graphics and Vision:**
   - **3D Rendering and Lighting:** The dot product is essential in computer graphics, particularly in determining the angle between light sources and surfaces, known as "shading." When rendering 3D objects, the dot product helps calculate how light reflects on surfaces, influencing the object's appearance.
   - **Facial Recognition:** In computer vision, the dot product can measure the similarity between different images or shapes. It's useful in facial recognition technologies, comparing the alignment and features of faces.

**3. Business:**
   - **Decision Making in Investments:** In finance, portfolio managers use the dot product to diversify asset portfolios. They can project one asset's returns onto another, helping in understanding correlations between different assets and making informed investment decisions.
   - **Market Strategy Alignment:** Businesses can use dot product calculations to align market strategies with consumer trends by treating market factors and strategy elements as vectors. The result helps in understanding the degree of alignment between a company's strategy and market needs.

**4. Data Science:**
   - **Cosine Similarity in Text Analysis:** In natural language processing (NLP), cosine similarity (calculated using the dot product) measures the similarity between two documents or sentences, helping in tasks like document clustering, topic modeling, or sentiment analysis.
   - **Recommendation Systems:** Dot product is used in recommendation engines, common in e-commerce and online streaming platforms. By treating customer preferences and product features as vectors, the dot product helps in identifying customer preferences, thereby suggesting items similar to their past purchases or views.
   - **Machine Learning Algorithms:** Several machine learning algorithms, especially in deep learning (like convolutional neural networks), use dot products to calculate weights' impact on inputs in their layers, significantly affecting the network's performance and results.

**5. Healthcare:**
   - **Genomic Research:** In bioinformatics, researchers use the dot product to measure the similarity between different genetic sequences, aiding in understanding genetic diseases, evolution, and traits inheritance.

In [ ]:
u = np.array([1,2,3])  # 1D   >>> same as in maths/physics that we studied
v = np.array([2,5,9])
u.dot(v)

39

In [ ]:
u.dot(v.T)

39

In [ ]:
u = u.reshape(-1,1)  # 2D
v = v.reshape(-1,1)  # 2D
# u, v
print(u.dot(v))


ValueError: ignored

In [ ]:
u = u.reshape(1,-1)  # 2D >> row vector
v = v.reshape(-1,1)  # 2D >> col vector
# u, v
print(u.dot(v))

[[39]]


In [ ]:
A

array([[   1,    5,   28],
       [   4,   20,  112],
       [  50,  250, 1400]])

In [ ]:
A.flatten()

array([   1,    5,   28,    4,   20,  112,   50,  250, 1400])

# Vector Norm
 The length of the vector is referred to as the vector norm or the vector’s magnitude.It is calculated using some measure that summarizes the distance of the vector from the origin of the vector space.

 Norms are functions that assign a strictly positive length or size to vectors in a vector space, except for the zero vector, which is assigned a length of zero. In mathematical optimization and computer science, particularly data analysis and machine learning, different types of norms (L1, L2, Max-norm) are used to evaluate functions or algorithms' performance, especially as a part of loss functions.

Here's how L1-norm, L2-norm, and Max-norm are applied in real-world scenarios, business domains, and data science/machine learning:

**1. L1-Norm (Least Absolute Deviations/Manhattan Distance):**

- **Feature Selection in Machine Learning:** L1 regularization technique (often called LASSO) tends to shrink less important feature's coefficients effectively to zero, thus helping in feature selection and making the model simpler and interpretable.
  
- **Robustness to Outliers in Statistics and Data Science:** In scenarios where data contains a lot of outliers, using the L1-norm can be more robust since it leads to models that are less sensitive to outliers compared to models using L2-norm.

- **Signal Processing:** In compressed sensing, L1-norm minimization is used in reconstructing a signal from sparse data or measurements.

- **Finance:** In portfolio construction, the L1-norm is used in the optimization problem to impose sparsity constraints on portfolio weights, ensuring diversification.

**2. L2-Norm (Least Squares/Euclidean Distance):**

- **Data Fitting in Statistics and Machine Learning:** L2-norm is widely used in the least squares method for data fitting. The approach minimizes the sum of square differences between the observed and predicted values, making it particularly sensitive to outliers but excellent for data with Gaussian noise.

- **Regularization in Machine Learning:** Known as Ridge regression, imposing an L2-norm penalty on regression coefficients constrains them, making the learning algorithm less prone to overfitting and improving model generalization.

- **Navigation and GPS:** L2-norm is used in Euclidean distance calculation between points, relevant in systems requiring precision, like GPS applications where you need the actual shortest path.

- **Healthcare:** In medical imaging, L2-norm is used in various reconstruction algorithms to improve image quality and detail.

**3. Max-Norm (Chebyshev Norm):**

- **Infinity Norm in Optimization Problems:** Max-norm (also known as infinity norm) is used in optimization problems where you want to minimize the maximum absolute value of the components of a vector. It's useful in operations research for handling "worst-case" scenarios.

- **Computer Graphics:** In designing graphical filters, especially in texture mapping, the Max-norm helps in reducing artifacts and defining resolution in image processing algorithms.

- **Supply Chain and Logistics:** For making decisions under uncertainty and handling worst-case scenarios in supply chain distribution and logistics, the Max-norm is used as a robust approach to minimize the maximum possible loss.

- **Neural Networks:** Regularization with Max-norm constraints in neural networks helps in preventing overfitting by limiting the weights' capacity, making the network generalize better to unseen data.

In [ ]:
v = np.array([1,2,3]) #

# calculate L1-norm
l1 = np.linalg.norm(v, 1)

l2 = np.linalg.norm(v,2)

print(l1, l2)

6.0 3.7416573867739413


In [ ]:
v = np.array([1,2,3]).reshape(-1, 1)

# calculate L1-norm
l1 = np.linalg.norm(v, 1)

l2 = np.linalg.norm(v,2)

print(l1, l2)

6.0 3.7416573867739413


In [ ]:
  np.pi

3.141592653589793

In [ ]:
maxnorm = np.linalg.norm(v, np.inf)
maxnorm

3.0

In [ ]:
# Cosine Similarity
import numpy as np

def cosine_similarity(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm_a = np.linalg.norm(vec1)
    norm_b = np.linalg.norm(vec2)
    return dot_product / (norm_a * norm_b)

# Example vectors
A = np.array([1, 2, 3])
B = np.array([-1, 5, 6])

# Calculate similarity
similarity = cosine_similarity(A, B)
print("Cosine similarity:", similarity)


Cosine similarity: 0.9164397149578765


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Note: the function returns a similarity matrix, where each cell [i][j] represents the cosine similarity between vectors i and j.
similarity = cosine_similarity(A.reshape(1,-1), B.reshape(1,-1))
print("Cosine similarity:", similarity[0][0])

Cosine similarity: 0.9164397149578765


In [ ]:
# Define a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Matrix A:")
print(A)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
from scipy.linalg import null_space
# Finding the null space using SciPy
nullspace = null_space(A)
print("\nNull space:")
print(nullspace)


Null space:
[[-0.40824829]
 [ 0.81649658]
 [-0.40824829]]


# Solving System of Linear Equations

2x + 3y + 5z = 10

3x + 2y + 1z = 8

2x + 1y + 2z = 6


In [ ]:
import numpy as np

# Define your matrices
A = np.array([
    [2, 3, 5],
    [3, 2, 1],
    [2, 1, 2]
])
B = np.array([10, 8, 6])

# Check if A is a square matrix
if A.shape[0] == A.shape[1]:
    # Find the inverse of matrix A
    try:
        A_inv = np.linalg.inv(A)
    except np.linalg.LinAlgError:
        # Not invertible. Skip this one.
        print("Matrix A is singular and does not have an inverse.")
        A_inv = None

    if A_inv is not None:
        # Solve for x by multiplying the inverse of A with B
        x = np.dot(A_inv, B)

        # Print the solution
        print(f"Solutions:\nx: {x[0]}\ny: {x[1]}\nz: {x[2]}")
else:
    print("Matrix A is not square.")


Solutions:
x: 1.8181818181818181
y: 0.9090909090909087
z: 0.7272727272727275


In [ ]:
# Coefficient matrix 'A' and constant matrix 'B'
A = np.array([[2, 3, 5],
              [3, 2, 1],
              [2, 1, 2]])
B = np.array([10, 8, 6])

# Solving the system of linear equations
x = np.linalg.solve(A, B)

# Print the solutions
print(f"Solutions:\nx: {x[0]}\ny: {x[1]}\nz: {x[2]}")


In [ ]:
# finding roots of a Polynomial
import numpy as np

# x^2 - 7x + 6 = 0
coefficients = [1, -7, 6]
roots = np.roots(coefficients)
print(roots)

[6. 1.]


# LU decomposition and QR factorization
LU decomposition and QR factorization are common techniques in linear algebra for solving linear equations, inverting matrices, and computing determinants efficiently. Below are examples of how to perform these decompositions in Python using the NumPy and SciPy libraries.

## 1. LU Decomposition
LU Decomposition factors a matrix as the product of a lower triangular matrix and an upper triangular matrix (along with a permutation matrix). Here's how you can do this in Python using the `scipy.linalg.lu` function.

In the coe below, `A` is the matrix you want to decompose, and `P`, `L`, and `U` are the permutation, lower triangular, and upper triangular matrices, respectively.

In [ ]:
import numpy as np
from scipy.linalg import lu

# Define a square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
])

# Perform LU decomposition
P, L, U = lu(A)

print("Original Matrix:")
print(A)
print("\nP = ")
print(P)
print("\nL = ")
print(L)
print("\nU = ")
print(U)


Original Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

P = 
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

L = 
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

U = 
[[ 7.          8.         10.        ]
 [ 0.          0.85714286  1.57142857]
 [ 0.          0.         -0.5       ]]


## 2. QR Factorization
QR factorization decomposes a matrix into a product of an orthogonal matrix and an upper triangular matrix. Here's how you can perform QR factorization using NumPy with the `numpy.linalg.qr` function.

In the code below, `A` is the matrix you want to factorize, and `Q` and `R` are the orthogonal and upper triangular matrices, respectively.

In [ ]:
import numpy as np

# Define a matrix
A = np.array([
    [12, -51, 4],
    [6, 167, -68],
    [-4, 24, -41]
])

# Perform QR factorization
Q, R = np.linalg.qr(A)

print("Original Matrix:")
print(A)
print("\nQ = ")
print(Q)
print("\nR = ")
print(R)

Original Matrix:
[[ 12 -51   4]
 [  6 167 -68]
 [ -4  24 -41]]

Q = 
[[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]

R = 
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


# MAtrix Inverse using LU Decomposition

LU decomposition can be utilized to calculate the inverse of a matrix \( A \) efficiently. The basic idea is to use the LU decomposition of \( A \) to solve the system \( AX = I \) for \( X \), where \( I \) is the identity matrix, and \( X \) will be the inverse of \( A \).

Here's a step-by-step breakdown:

1. Decompose the matrix \( A \) into its LU components: \( A = LU \).
2. For each column \( i \) of the identity matrix \( I \):
    - a. Solve the lower triangular system \( LY = I[:,i] \) for \( Y \).
    - b. Solve the upper triangular system \( UX = Y \) for \( X \).
    - c. The resulting \( X \) is the \( i^{th} \) column of \( A^{-1} \).

Remember, not all matrices have an inverse. If \( A \) is singular, then this process won't provide a meaningful result.

In [ ]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve

def matrix_inverse_using_lu(A):
    # Retrieve the number of rows (or columns) for the square matrix A
    n = A.shape[0]

    # Perform LU decomposition on the input matrix A.
    # 'lu' is the combined form of lower and upper triangular matrices.
    # 'piv' holds the pivot indices showing row swaps made during the decomposition process.
    lu, piv = lu_factor(A)

    # Create an identity matrix of size 'n x n'. This matrix serves as the right-hand side
    # of the equation system to be solved for finding the inverse. Each column in the identity
    # matrix is used in turn to solve the equation system.
    I = np.eye(n)

    # Initialize an empty matrix of zeros with the same shape as A to store the inverse.
    # The data type is specified as float64 for higher precision.
    invA = np.zeros_like(A, dtype=np.float64)

    # Iterate over each column of the identity matrix.
    for i in range(n):
        # For each column, solve the equation system 'Ax = I[:, i]' where 'A' is the original
        # matrix, 'x' is the column vector of the inverse we are solving for, and 'I[:, i]'
        # is the current column of the identity matrix.
        # The function 'lu_solve' is used with the LU decomposition results and the current
        # column of the identity matrix to find each 'x' (each column of the inverse matrix).
        invA[:, i] = lu_solve((lu, piv), I[:, i])

    # After finding all columns of the inverse matrix, return the completed inverse.
    return invA

# Define a matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
], dtype=np.float64)  # Ensure the dtype is float for precision

# Calculate the inverse using LU decomposition
A_inv_lu = matrix_inverse_using_lu(A)

# Using NumPy's built-in function to find the inverse
A_inv_np = np.linalg.inv(A)

# Print the results
print("Inverse using LU decomposition:")
print(A_inv_lu)
print("\nInverse using NumPy:")
print(A_inv_np)

# Verify if the results are approximately equal
if np.allclose(A_inv_lu, A_inv_np):
    print("\nBoth methods give approximately the same result.")
else:
    print("\nResults are different.")

# Validation by checking A_inv * A = I
print("\nValidation by multiplying the original matrix by its inverse:")
result = np.dot(A, A_inv_lu)
print(result)

# Check if the result is close to the identity matrix
identity_matrix = np.eye(A.shape[0])
if np.allclose(result, identity_matrix):
    print("\nThe result is approximately an identity matrix. The minor discrepancies are due to floating-point precision.")
else:
    print("\nThe result significantly deviates from an identity matrix. There may be an issue with the calculations.")

Inverse using LU decomposition:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]

Inverse using NumPy:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]

Both methods give approximately the same result.

Validation by multiplying the original matrix by its inverse:
[[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]]

The result is approximately an identity matrix. The minor discrepancies are due to floating-point precision.


In [ ]:
import scipy.linalg as la
import numpy as np

def inverse_via_lu(A):
    # Step 1: Perform LU Decomposition
    P, L, U = la.lu(A)

    # Step 2: Solve for the inverse
    n = A.shape[0]
    I = np.eye(n)
    A_inv = np.zeros_like(A)

    for i in range(n):
        b = I[:, i]  # This selects the i-th column of the Identity matrix
        y = la.solve_triangular(L, np.dot(P.T, b), lower=True)  # Solve Ly = Pb for y
        x = la.solve_triangular(U, y, lower=False)  # Now solve Ux = y for x
        A_inv[:, i] = x  # Place the solution in the appropriate column

    return A_inv

# Define a matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
], dtype=np.float64)  # Ensure the dtype is float for precision

A_inv = inverse_via_lu(A)

print("Original Matrix:")
print(A)

print("\nInverse Matrix:")
print(A_inv)

# Verification: multiplying a matrix by its inverse should yield the identity matrix
print("\nA * A_inv:")
print(np.dot(A, A_inv))


Original Matrix:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]]

Inverse Matrix:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]

A * A_inv:
[[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]]


This function first decomposes the matrix `A` into `P`, `L`, and `U` matrices (permutation, lower, and upper triangular matrices, respectively). It then solves the system of equations Ly = Pb and Ux = y for each column of the identity matrix, effectively solving the equation Ax = I, where `I` is the identity matrix. The solutions `x` are the columns of the inverse matrix.