In [ ]:
# Linear Regression using Linear Algebra concepts

# Objective: "Best" straight line fit to these data points
# CLaim: The "Best" fit will have minimum Error = Y_hat - Y

# Y_hat = w0 + x1.X
# w0 = intercept term
# w1 = slope of the best fit line

# We'll be actually minimizing the SSE or MSE (Mean Squared Error)


In [1]:
import numpy as np

# define your X and Y as NumPy Arrays
X = np.array([1,3,5])
Y = np.array([4.8,12.4,15.5])

# np.polyfit function does a 1-dimensional Polynomial fitting
# and the np.poly1d function convers the polynomial coefficents
# into a polynomila object that can be evaluated
p = np.poly1d(np.polyfit(X,Y,1))
print(p)
# [OUTPUT]:
# 2.675 x + 2.875

 
2.675 x + 2.875


In [13]:
X = np.array([1,3,5]).reshape(-1, 1)
Y = np.array([4.8,12.4,15.5]).reshape(-1,1)

ones = np.ones(X.shape[0]).reshape(-1,1)

X_new = np.hstack([ones, X])
X_new

array([[1., 1.],
       [1., 3.],
       [1., 5.]])

In [9]:
# np.matmul(X_new.T, X_new)
X_new.T.dot(X_new)

array([[ 3.,  9.],
       [ 9., 35.]])

In [10]:
np.linalg.inv(X_new.T.dot(X_new))

array([[ 1.45833333, -0.375     ],
       [-0.375     ,  0.125     ]])

In [11]:
np.linalg.inv(X_new.T.dot(X_new)).dot(X_new.T)

array([[ 1.08333333e+00,  3.33333333e-01, -4.16666667e-01],
       [-2.50000000e-01, -2.77555756e-17,  2.50000000e-01]])

In [12]:
# Final Solution
np.linalg.inv(X_new.T.dot(X_new)).dot(X_new.T).dot(Y)

array([[2.875],
       [2.675]])

In [14]:
np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)

array([[3.41428571]])