In [4]:
pwd

'D:\\OneDrive\\Google Drive Files\\Training\\IIM Indore'

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("BostonHousing.csv")
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [6]:
path = r"D:\OneDrive\Google Drive Files\Training\1 MASTER\3. EDA and Data Visualisation\DSMP - ML\SBSA_DSMP_SORTED\SBSA DOWNLOADS\Jupyter Notebooks ML week 9\Washington House Prediction"
filename = path + '\data.csv'
df1 = pd.read_csv(filename)
df1.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [9]:
df.isna().sum()   # the number of null or missing values in each column

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [11]:
df.describe().T.round(2)  # quick statistical summary of the dataset

count    mean     std     min     25%     50%     75%     max
crim     506.0    3.61    8.60    0.01    0.08    0.26    3.68   88.98
zn       506.0   11.36   23.32    0.00    0.00    0.00   12.50  100.00
indus    506.0   11.14    6.86    0.46    5.19    9.69   18.10   27.74
chas     506.0    0.07    0.25    0.00    0.00    0.00    0.00    1.00
nox      506.0    0.55    0.12    0.38    0.45    0.54    0.62    0.87
rm       506.0    6.28    0.70    3.56    5.89    6.21    6.62    8.78
age      506.0   68.57   28.15    2.90   45.02   77.50   94.07  100.00
dis      506.0    3.80    2.11    1.13    2.10    3.21    5.19   12.13
rad      506.0    9.55    8.71    1.00    4.00    5.00   24.00   24.00
tax      506.0  408.24  168.54  187.00  279.00  330.00  666.00  711.00
ptratio  506.0   18.46    2.16   12.60   17.40   19.05   20.20   22.00
b        506.0  356.67   91.29    0.32  375.38  391.44  396.22  396.90
lstat    506.0   12.65    7.14    1.73    6.95   11.36   16.96   37.97
medv     506.0   22.53    9.20    5.00   17.02   21.20   25.00   50.00

In [12]:
df.skew()  # skewness values for each column

crim       5.223149
zn         2.225666
indus      0.295022
chas       3.405904
nox        0.729308
rm         0.403612
age       -0.598963
dis        1.011781
rad        1.004815
tax        0.669956
ptratio   -0.802325
b         -2.890374
lstat      0.906460
medv       1.108098
dtype: float64

In [14]:
df.corr().round(2)

crim    zn  indus  chas   nox    rm   age   dis   rad   tax  ptratio  \
crim     1.00 -0.20   0.41 -0.06  0.42 -0.22  0.35 -0.38  0.63  0.58     0.29   
zn      -0.20  1.00  -0.53 -0.04 -0.52  0.31 -0.57  0.66 -0.31 -0.31    -0.39   
indus    0.41 -0.53   1.00  0.06  0.76 -0.39  0.64 -0.71  0.60  0.72     0.38   
chas    -0.06 -0.04   0.06  1.00  0.09  0.09  0.09 -0.10 -0.01 -0.04    -0.12   
nox      0.42 -0.52   0.76  0.09  1.00 -0.30  0.73 -0.77  0.61  0.67     0.19   
rm      -0.22  0.31  -0.39  0.09 -0.30  1.00 -0.24  0.21 -0.21 -0.29    -0.36   
age      0.35 -0.57   0.64  0.09  0.73 -0.24  1.00 -0.75  0.46  0.51     0.26   
dis     -0.38  0.66  -0.71 -0.10 -0.77  0.21 -0.75  1.00 -0.49 -0.53    -0.23   
rad      0.63 -0.31   0.60 -0.01  0.61 -0.21  0.46 -0.49  1.00  0.91     0.46   
tax      0.58 -0.31   0.72 -0.04  0.67 -0.29  0.51 -0.53  0.91  1.00     0.46   
ptratio  0.29 -0.39   0.38 -0.12  0.19 -0.36  0.26 -0.23  0.46  0.46     1.00   
b       -0.39  0.18  -0.36  0.05 -0.38  0.13 -0.27  0.29 -0.44 -0.44    -0.18   
lstat    0.46 -0.41   0.60 -0.05  0.59 -0.61  0.60 -0.50  0.49  0.54     0.37   
medv    -0.39  0.36  -0.48  0.18 -0.43  0.70 -0.38  0.25 -0.38 -0.47    -0.51   

            b  lstat  medv  
crim    -0.39   0.46 -0.39  
zn       0.18  -0.41  0.36  
indus   -0.36   0.60 -0.48  
chas     0.05  -0.05  0.18  
nox     -0.38   0.59 -0.43  
rm       0.13  -0.61  0.70  
age     -0.27   0.60 -0.38  
dis      0.29  -0.50  0.25  
rad     -0.44   0.49 -0.38  
tax     -0.44   0.54 -0.47  
ptratio -0.18   0.37 -0.51  
b        1.00  -0.37  0.33  
lstat   -0.37   1.00 -0.74  
medv     0.33  -0.74  1.00

In [16]:
corr_matrix = df.corr().round(2)
corr_matrix[np.abs(corr_matrix) > 0.6]

crim    zn  indus  chas   nox    rm   age   dis   rad   tax  ptratio  \
crim     1.00   NaN    NaN   NaN   NaN   NaN   NaN   NaN  0.63   NaN      NaN   
zn        NaN  1.00    NaN   NaN   NaN   NaN   NaN  0.66   NaN   NaN      NaN   
indus     NaN   NaN   1.00   NaN  0.76   NaN  0.64 -0.71   NaN  0.72      NaN   
chas      NaN   NaN    NaN   1.0   NaN   NaN   NaN   NaN   NaN   NaN      NaN   
nox       NaN   NaN   0.76   NaN  1.00   NaN  0.73 -0.77  0.61  0.67      NaN   
rm        NaN   NaN    NaN   NaN   NaN  1.00   NaN   NaN   NaN   NaN      NaN   
age       NaN   NaN   0.64   NaN  0.73   NaN  1.00 -0.75   NaN   NaN      NaN   
dis       NaN  0.66  -0.71   NaN -0.77   NaN -0.75  1.00   NaN   NaN      NaN   
rad      0.63   NaN    NaN   NaN  0.61   NaN   NaN   NaN  1.00  0.91      NaN   
tax       NaN   NaN   0.72   NaN  0.67   NaN   NaN   NaN  0.91  1.00      NaN   
ptratio   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN      1.0   
b         NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN      NaN   
lstat     NaN   NaN    NaN   NaN   NaN -0.61   NaN   NaN   NaN   NaN      NaN   
medv      NaN   NaN    NaN   NaN   NaN  0.70   NaN   NaN   NaN   NaN      NaN   

           b  lstat  medv  
crim     NaN    NaN   NaN  
zn       NaN    NaN   NaN  
indus    NaN    NaN   NaN  
chas     NaN    NaN   NaN  
nox      NaN    NaN   NaN  
rm       NaN  -0.61  0.70  
age      NaN    NaN   NaN  
dis      NaN    NaN   NaN  
rad      NaN    NaN   NaN  
tax      NaN    NaN   NaN  
ptratio  NaN    NaN   NaN  
b        1.0    NaN   NaN  
lstat    NaN   1.00 -0.74  
medv     NaN  -0.74  1.00

In [17]:
X = df.drop('medv', axis=1)
y = df['medv']
X.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  
0  396.90   4.98  
1  396.90   9.14  
2  392.83   4.03  
3  394.63   2.94  
4  396.90   5.33

In [19]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: medv, dtype: float64

In [25]:
X.shape, y.shape

((506, 13), (506,))

In [22]:
from sklearn.model_selection import train_test_split

# train_test_split  is a python function, so you can directly use it after import
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
X_train.shape, X_test.shape

((404, 13), (102, 13))

In [26]:
from sklearn.linear_model import LinearRegression

# LinearRegression is a CLASS, hence it has to be instantiated before use
LR = LinearRegression()

In [27]:
LR.fit(X_train, y_train)  # model training step
# "fitting" always means "learning something from data"
# So, in this case, the LR is learning the "optimal values of the model coefficinats"
# which are the slope(s) and intercept

LinearRegression()

In [29]:
LR.predict(X_test)   # model's predictions on the test set

array([28.99672362, 36.02556534, 14.81694405, 25.03197915, 18.76987992,
       23.25442929, 17.66253818, 14.34119   , 23.01320703, 20.63245597,
       24.90850512, 18.63883645, -6.08842184, 21.75834668, 19.23922576,
       26.19319733, 20.64773313,  5.79472718, 40.50033966, 17.61289074,
       27.24909479, 30.06625441, 11.34179277, 24.16077616, 17.86058499,
       15.83609765, 22.78148106, 14.57704449, 22.43626052, 19.19631835,
       22.43383455, 25.21979081, 25.93909562, 17.70162434, 16.76911711,
       16.95125411, 31.23340153, 20.13246729, 23.76579011, 24.6322925 ,
       13.94204955, 32.25576301, 42.67251161, 17.32745046, 27.27618614,
       16.99310991, 14.07009109, 25.90341861, 20.29485982, 29.95339638,
       21.28860173, 34.34451856, 16.04739105, 26.22562412, 39.53939798,
       22.57950697, 18.84531367, 32.72531661, 25.0673037 , 12.88628956,
       22.68221908, 30.48287757, 31.52626806, 15.90148607, 20.22094826,
       16.71089812, 20.52384893, 25.96356264, 30.61607978, 11.59

In [30]:
LR.score(X_test, y_test)   # R^2 for the LR model on the test set

0.6687594935356317

In [31]:
LR.score(X_train, y_train)   # R^2 for the LR model on the test set

0.7508856358979673

In [32]:
LR.coef_

array([-1.13055924e-01,  3.01104641e-02,  4.03807204e-02,  2.78443820e+00,
       -1.72026334e+01,  4.43883520e+00, -6.29636221e-03, -1.44786537e+00,
        2.62429736e-01, -1.06467863e-02, -9.15456240e-01,  1.23513347e-02,
       -5.08571424e-01])

In [33]:
LR.intercept_

30.24675099392349

In [34]:
coeff_df = pd.DataFrame(LR.coef_, index=X.columns, columns=['Model Coeff'])
coeff_df

Model Coeff
crim       -0.113056
zn          0.030110
indus       0.040381
chas        2.784438
nox       -17.202633
rm          4.438835
age        -0.006296
dis        -1.447865
rad         0.262430
tax        -0.010647
ptratio    -0.915456
b           0.012351
lstat      -0.508571

In [37]:
ones = np.ones(X.shape[0]).reshape(-1, 1)
X_new = np.hstack([ones, X])
X_new

array([[1.0000e+00, 6.3200e-03, 1.8000e+01, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [1.0000e+00, 2.7310e-02, 0.0000e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [1.0000e+00, 2.7290e-02, 0.0000e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [1.0000e+00, 6.0760e-02, 0.0000e+00, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0000e+00, 1.0959e-01, 0.0000e+00, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [1.0000e+00, 4.7410e-02, 0.0000e+00, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)

In [40]:
X_train.shape

(404, 14)

## Using the OLS Normal Equation

In [41]:
np.linalg.inv(X_train.T.dot(X_train)).dot(X_train.T).dot(y_train)
# Same coeff as obtained by using the LinearRegression class from sklearn !!

array([ 3.02467510e+01, -1.13055924e-01,  3.01104641e-02,  4.03807204e-02,
        2.78443820e+00, -1.72026334e+01,  4.43883520e+00, -6.29636221e-03,
       -1.44786537e+00,  2.62429736e-01, -1.06467863e-02, -9.15456240e-01,
        1.23513347e-02, -5.08571424e-01])

In [44]:
## Scaling of the features before the model is built
X = df.drop('medv', axis=1)
y = df['medv']
X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [45]:
from sklearn.preprocessing import StandardScaler

SC = StandardScaler()   # tranformer class
X_train_std = SC.fit_transform(X_train)  # standardising the training features
X_test_std = SC.transform(X_test) # standardising the test features

# Always do a fit_tranform on the trianing set, before tranforming the test set
# "fitting" always means "learning something from data"
# in this case fit is calculating the means and std_dev for each feature and preparing the transformer

In [46]:
LR = LinearRegression()   # estimator class
LR.fit(X_train_std,y_train)  # fitting the LR algo on the standardized data

LinearRegression()

In [47]:
LR.predict(X_test_std)

array([28.99672362, 36.02556534, 14.81694405, 25.03197915, 18.76987992,
       23.25442929, 17.66253818, 14.34119   , 23.01320703, 20.63245597,
       24.90850512, 18.63883645, -6.08842184, 21.75834668, 19.23922576,
       26.19319733, 20.64773313,  5.79472718, 40.50033966, 17.61289074,
       27.24909479, 30.06625441, 11.34179277, 24.16077616, 17.86058499,
       15.83609765, 22.78148106, 14.57704449, 22.43626052, 19.19631835,
       22.43383455, 25.21979081, 25.93909562, 17.70162434, 16.76911711,
       16.95125411, 31.23340153, 20.13246729, 23.76579011, 24.6322925 ,
       13.94204955, 32.25576301, 42.67251161, 17.32745046, 27.27618614,
       16.99310991, 14.07009109, 25.90341861, 20.29485982, 29.95339638,
       21.28860173, 34.34451856, 16.04739105, 26.22562412, 39.53939798,
       22.57950697, 18.84531367, 32.72531661, 25.0673037 , 12.88628956,
       22.68221908, 30.48287757, 31.52626806, 15.90148607, 20.22094826,
       16.71089812, 20.52384893, 25.96356264, 30.61607978, 11.59

In [49]:
LR.coef_

array([-1.00213533,  0.69626862,  0.27806485,  0.7187384 , -2.0223194 ,
        3.14523956, -0.17604788, -3.0819076 ,  2.25140666, -1.76701378,
       -2.03775151,  1.12956831, -3.61165842])

In [50]:
LR.score(X_test_std, y_test)   # R^2 value after scaling

0.668759493535632

In [61]:
# Also scaling Y
SC_y = StandardScaler()   # tranformer class
y_train_std = SC_y.fit_transform(y_train.values.reshape(-1,1)) # standardising the training features
y_test_std = SC_y.transform(y_test.values.reshape(-1,1))

In [62]:
y_train_std

array([[-1.15835310e+00],
       [-3.10767296e-01],
       [-3.64411967e-01],
       [-1.00814802e+00],
       [-4.93159177e-01],
       [ 1.93492610e-01],
       [-1.82020086e-01],
       [ 2.04221544e-01],
       [-1.51240792e+00],
       [ 5.04631701e-01],
       [-2.24935823e-01],
       [ 1.43804897e+00],
       [ 9.44518002e-01],
       [-1.19053990e+00],
       [ 1.82429061e+00],
       [-9.54503347e-01],
       [-1.06917547e-01],
       [ 9.69322024e-02],
       [-5.57532783e-01],
       [ 1.72034742e-01],
       [-1.50167899e+00],
       [-3.85869836e-01],
       [ 2.68595149e-01],
       [-2.57122626e-01],
       [ 3.25585973e-02],
       [ 1.62044086e+00],
       [-7.72111466e-01],
       [ 2.42511092e+00],
       [-7.61382532e-01],
       [-2.10860736e-02],
       [-8.90129742e-01],
       [-4.39514507e-01],
       [-5.36074914e-01],
       [-7.18466795e-01],
       [-2.35664757e-01],
       [ 9.44518002e-01],
       [ 6.76294648e-01],
       [-7.72111466e-01],
       [-5.6

In [63]:
LR1 = LinearRegression()   # estimator class
LR1.fit(X_train_std,y_train_std)  # fitting the LR algo on the standardized data

LinearRegression()

In [67]:
LR1.predict(X_test_std)[:5]   # model's predictions are the z_scores of the MEDV

array([[ 0.66521419],
       [ 1.41933399],
       [-0.85612502],
       [ 0.23983937],
       [-0.43201714]])

In [69]:
LR1.score(X_test_std, y_test_std)   # R^2 value after scaling
# Concl.: EVEN after standardizing the y values, the model remiain the same.

0.6687594935356319

In [71]:
SC_y.inverse_transform(np.array([[ 0.66521419]]))  # converting the prediction in the original y_scale

array([[28.99672359]])

In [73]:
SC_y.inverse_transform(LR1.predict(X_test_std) ) [:5] # getting the predictions in the original y_sclae

array([[28.99672362],
       [36.02556534],
       [14.81694405],
       [25.03197915],
       [18.76987992]])

## Gradient Descent example from the slide

In [74]:
import numpy as np

# define your X and Y as NumPy Arrays
X = np.array([1,3,5])
Y = np.array([4.8,11.4,17.5])

# np.polyfit function does a 1-dimensional Polynomial fitting
# and the np.poly1d function convers the polynomial coefficents
# into a polynomila object that can be evaluated
p = np.poly1d(np.polyfit(X,Y,1))
print(p)

 
3.175 x + 1.708
